### ISSUE TITLE
Notification does not show metadata on Android

### ISSUE THREAD

**Issue by Yesterday17** [erikas-taroza/simple_audio#20]
## Behavior

1. On my app the notification does not appear at all.
2. Sometimes the notification appears. But no metadata would be displayed. The control buttons are present and work well.

## Info

- Android version: 12

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.9.0-12.0.pre.1, on Manjaro Linux 6.1.19-1-MANJARO, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

## Error

The only error I found was:

```
W/MediaSessionCompat(15456): Couldn't find a unique registered media button receiver in the given context.
D/CompatibilityChangeReporter(15456): Compat change id reported: 160794467; UID 10414; state: ENABLED
E/MethodChannel#simple_audio(15456): Failed to handle method call
E/MethodChannel#simple_audio(15456): java.lang.NullPointerException
E/MethodChannel#simple_audio(15456): 	at com.erikas.simple_audio.SimpleAudioPlugin.onMethodCall(SimpleAudioPlugin.kt:89)
E/MethodChannel#simple_audio(15456): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#simple_audio(15456): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#simple_audio(15456): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#simple_audio(15456): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#simple_audio(15456): 	at android.os.Handler.handleCallback(Handler.java:980)
E/MethodChannel#simple_audio(15456): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/MethodChannel#simple_audio(15456): 	at android.os.Looper.loopOnce(Looper.java:238)
E/MethodChannel#simple_audio(15456): 	at android.os.Looper.loop(Looper.java:357)
E/MethodChannel#simple_audio(15456): 	at android.app.ActivityThread.main(ActivityThread.java:8098)
E/MethodChannel#simple_audio(15456): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#simple_audio(15456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#simple_audio(15456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/flutter (15456): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (15456): 	at com.erikas.simple_audio.SimpleAudioPlugin.onMethodCall(SimpleAudioPlugin.kt:89)
E/flutter (15456): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (15456): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (15456): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (15456): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (15456): 	at android.os.Handler.handleCallback(Handler.java:980)
E/flutter (15456): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/flutter (15456): 	at android.os.Looper.loopOnce(Looper.java:238)
E/flutter (15456): 	at android.os.Looper.loop(Looper.java:357)
E/flutter (15456): 	at android.app.ActivityThread.main(ActivityThread.java:8098)
E/flutter (15456): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (15456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (15456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/flutter (15456): )
E/flutter (15456): #0      StandardMethodCodec.decodeEnvelope
E/flutter (15456): #1      MethodChannel._invokeMethod
E/flutter (15456): <asynchronous suspension>
```

Not sure whether flutter version is a problem. I would try with flutter stable this weekend.

**Comment by erikas-taroza** [comment]
I tried on the master channel and everything works.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.9.0-17.0.pre.26, on Fedora Linux 37 (Workstation Edition) 6.2.7-200.fc37.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by erikas-taroza** [comment]
Closing for inactivity.
